FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-tk \
    dnsmasq \
    x11-apps \
    xfce4 \
    xfce4-terminal \
    dbus-x11 \
    --no-install-recommends

ENV DISPLAY=:0
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app
COPY requirements.txt .
COPY service/ ./service/
COPY dnsmasq/dnsmasq.conf /etc/dnsmasq.conf

RUN pip3 install -r requirements.txt

RUN systemctl enable dnsmasq

CMD ["xfce4-terminal"]